FROM python:3.9-slim

WORKDIR /app
# Copy requirements and install dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY . .

# Expose the port Streamlit uses
EXPOSE 8501

# Set environment variables (optional, for .env usage)
ENV PYTHONUNBUFFERED=1
# Add the app directory to the Python path
ENV PYTHONPATH=/app

WORKDIR /app/worker_upload_excel
CMD ["python", "app.py"]